version: '3.4'

services:
  openSleigh.Sample11.infrastructure.sql:
    container_name: openSleigh.Sample11.infrastructure.sql    
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Sup3r_p4ssword123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433     
  
  openSleigh.Sample11.infrastructure.rabbitmq:        
    image: rabbitmq:3-management-alpine
    container_name: openSleigh.Sample11.infrastructure.rabbitmq    
    restart: always
    environment:
     RABBITMQ_DEFAULT_VHOST: "/"
    ports:     
      - "15671:15671"
      - "15672:15672"   
      - "5672:5672"